//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookExWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHasInfo
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
