//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookExWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHasBook
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public long BookID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.DateTime LstUpdate { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Book Book { get; set; }
    }
}
